name: "sdk ci"

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths: 
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Run Deno TestS
        run: deno task test

      - name: Run Node Tests
        run: npm test
        working-directory: ./npm

      - name: Run Bun Tests
        run: npm test:bun
        working-directory: ./npm

      - name: "Npm Audit"
        run: npm audit
        working-directory: ./npm

      - name: Publish Dry Run
        run: deno task publish:test
        if: matrix.os == 'ubuntu-latest'
