name: "publish"

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        registry-url: 'https://registry.npmjs.org'

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Bun Install
      run: deno task bun:install

    - name: JSR Publish
      run: deno publish

    - name: NPM Publish
      run: npm publish --provenance --access public
      working-directory: ./npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    